
[package]
name = "ambient_intent"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_std = { path = "../std" }
ambient_ecs = { path = "../ecs" }
ambient_network = { path = "../network" }
ambient_rpc = { path = "../rpc" }
ambient_ui = { path = "../ui" }
ambient_editor_derive = { path = "../editor_derive" }
ambient_element = { path = "../element" }
tracing = { workspace = true }
itertools = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
atomic_refcell = { workspace = true }
futures = { workspace = true }
parking_lot = { workspace = true }
profiling = { workspace = true }
chrono = { workspace = true }

[features]
intent_block_detection = []

[dev-dependencies]
pretty_assertions = { workspace = true }