[package]
name = "ambient_ui_components"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_element = { path = "../element", default-features = false }
ambient_guest_bridge = { path = "../guest_bridge", default-features = false }
ambient_window_types = { path = "../window_types" }
cb = { path = "../../libs/cb" }
ambient_color = { path = "../../libs/color" }
glam = { workspace = true }
itertools = { workspace = true }
futures = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[features]
native = ["ambient_window_types/native"]
