[package]
name = "ambient_api_macros"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Macros for the Ambient API"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/ambient_api_macros"
repository = "https://github.com/AmbientRun/Ambient"

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0"
quote = "1.0"
serde = { version = "1.0.152", features = ["derive"] }
syn = { version = "1.0", features = ["full"] }
toml = "0.7.1"
proc-macro2 = "1.0"

[dev-dependencies]
indoc = "2.0.0"
