[package]
name = "ambient_rustc"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"

[dependencies]
anyhow = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
