[package]
name = "ambient_ui"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_sys = { path = "../sys" }
ambient_std = { path = "../std" }
ambient_ecs = { path = "../ecs" }
ambient_gpu = { path = "../gpu" }
ambient_core = { path = "../core" }
ambient_meshes = { path = "../meshes" }
ambient_element = { path = "../element" }
ambient_input = { path = "../input" }
ambient_renderer = { path = "../renderer" }
ambient_layout = { path = "../layout" }
ambient_text = { path = "../text" }
ambient_rect = { path = "../rect" }
ambient_ui_components = { path = "../ui_components", features = ["native"] }
ambient_editor_derive = { path = "../editor_derive" }
ambient_window_types = { path = "../window_types", features = ["native"] }
glam = { workspace = true }
winit = { workspace = true }
itertools = { workspace = true }
futures = { workspace = true }
closure = { workspace = true }
log = { workspace = true }
wgpu = { workspace = true }
indexmap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
parking_lot = { workspace = true }
thiserror = { workspace = true }
ordered-float = { workspace = true }
tokio = { workspace = true }
bytemuck = { workspace = true }
convert_case = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
ambient_app = { path = "../app" }
ambient_cameras = { path = "../cameras" }
fixed-vec-deque = { workspace = true }
tokio = { workspace = true }
itertools = { workspace = true }
rand = { workspace = true }
env_logger = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[features]
hotload-includes = ['ambient_std/hotload-includes']


[target.'cfg(not(target_os = "unknown"))'.dependencies]
arboard = { workspace = true }
