
[package]
name = "ambient_world_audio"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_ecs = { path = "../ecs" }
ambient_app = { path = "../app" }
ambient_ui = { path = "../ui" }
ambient_core = { path = "../core" }
ambient_element = { path = "../element" }
ambient_std = { path = "../std" }
ambient_audio = { path = "../audio" }
ambient_network = { path = "../network" }
parking_lot = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
dashmap = { workspace = true }
slotmap = { workspace = true }
thiserror = { workspace = true }
flume = { workspace = true }
futures = { workspace = true }
indexmap = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
rand_chacha = "0.3.1"
itertools = { workspace = true }
closure = { workspace = true }
glam = { workspace = true }
ordered-float = { workspace = true }
profiling = { workspace = true }
atomic_refcell = "0.1.8"
tracing = { workspace = true }
derive_more = { workspace = true }

[dev-dependencies]
tracing-subscriber = "0.3"
ambient_renderer = { path = "../renderer" }
ambient_primitives = { path = "../primitives" }
ambient_cameras = { path = "../cameras" }

[features]
hotload-includes = ['ambient_std/hotload-includes']
