[package]
name = "ambient_gizmos"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_std = { path = "../std" }
ambient_ecs = { path = "../ecs" }
ambient_gpu = { path = "../gpu" }
ambient_core = { path = "../core" }
ambient_meshes = { path = "../meshes" }
ambient_renderer = { path = "../renderer" }
dashmap = { workspace = true }
glam = { workspace = true }
bytemuck = { workspace = true }
wgpu = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
once_cell = "1.13.0"
profiling = { workspace = true }

[dev-dependencies]
ambient_app = { path = "../app" }
ambient_cameras = { path = "../cameras" }

[features]
hotload-includes = ['ambient_std/hotload-includes']
