[package]
name = "ambient_primitives"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_ecs = { path = "../ecs" }
ambient_element = { path = "../element" }
ambient_core = { path = "../core" }
ambient_gpu = { path = "../gpu" }
ambient_std = { path = "../std" }
ambient_renderer = { path = "../renderer" }
ambient_meshes = { path = "../meshes" }
glam = { workspace = true }
