
[package]
name = "ambient_physics"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_ecs = { path = "../ecs" }
ambient_element = { path = "../element" }
ambient_ui = { path = "../ui" }
ambient_std = { path = "../std" }
ambient_editor_derive = { path = "../editor_derive" }
ambient_core = { path = "../core" }
ambient_meshes = { path = "../meshes" }
ambient_network = { path = "../network" }
ambient_gizmos = { path = "../gizmos" }
ambient_model = { path = "../model" }
ambient_primitives = { path = "../primitives" }
physxx = { path = "../../libs/physxx" }
serde = { workspace = true }
serde_json = { workspace = true }
glam = { workspace = true }
itertools = { workspace = true }
futures = { workspace = true }
rand = { workspace = true }
async-trait = { workspace = true }
parking_lot = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
profiling = { workspace = true }
ordered-float = { workspace = true }
once_cell = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }

[dev-dependencies]
ambient_app = { path = "../app" }
ambient_renderer = { path = "../renderer" }
ambient_primitives = { path = "../primitives" }
ambient_cameras = { path = "../cameras" }
