[package]
name = "ambient_prefab"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_ecs = { path = "../ecs" }
ambient_core = { path = "../core" }
ambient_model = { path = "../model" }
ambient_network = { path = "../network" }
ambient_physics = { path = "../physics" }
ambient_rpc = { path = "../rpc" }
ambient_std = { path = "../std" }
ambient_decals = { path = "../decals" }
glam = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
log = { workspace = true }
serde_json = { workspace = true }
