[package]
name = "ambient_renderer"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_sys = { path = "../sys" }
ambient_std = { path = "../std" }
ambient_ecs = { path = "../ecs" }
ambient_gpu = { path = "../gpu" }
ambient_core = { path = "../core" }
ambient_meshes = { path = "../meshes" }
wgpu = { workspace = true }
glam = { workspace = true }
itertools = { workspace = true }
ordered-float = { workspace = true }
serde = { workspace = true }
derive_more = { workspace = true }
downcast-rs = { workspace = true }
profiling = { workspace = true }
bytemuck = { workspace = true }
smallvec = { workspace = true }
log = { workspace = true }
parking_lot = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
ambient_app = { path = "../app" }
ambient_element = { path = "../element" }
ambient_gizmos = { path = "../gizmos" }
ambient_model_import = { path = "../model_import" }
ambient_cameras = { path = "../cameras" }
ambient_primitives = { path = "../primitives" }
env_logger = { workspace = true }
winit = { workspace = true }

[features]
hotload-includes = ['ambient_std/hotload-includes']
