[package]
name = "ambient_model_import"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_std = { path = "../std" }
ambient_core = { path = "../core" }
ambient_ecs = { path = "../ecs" }
ambient_renderer = { path = "../renderer" }
ambient_element = { path = "../element" }
ambient_ui = { path = "../ui" }
ambient_physics = { path = "../physics" }
ambient_model = { path = "../model" }
ambient_animation = { path = "../animation" }
ambient_editor_derive = { path = "../editor_derive" }
physxx = { path = "../../libs/physxx" }
glam = { workspace = true }
env_logger = { workspace = true }
gltf = { workspace = true }
image = { workspace = true }
base64 = { workspace = true }
async-trait = { workspace = true }
bincode = { workspace = true }
bytemuck = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
itertools = { workspace = true }
reqwest = { workspace = true }
futures = { workspace = true }
async-recursion = { workspace = true }
fbxcel = { workspace = true }
ordered-float = { workspace = true }
indexmap = { workspace = true }
log = { workspace = true }
relative-path = { workspace = true }
russimp = { workspace = true, optional = true}

[dev-dependencies]
ambient_app = { path = "../app" }
ambient_element = { path = "../element" }
ambient_gizmos = { path = "../gizmos" }
ambient_primitives = { path = "../primitives" }
ambient_cameras = { path = "../cameras" }
winit = { workspace = true }
