[package]
name = "ambient_project"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"

[dependencies]
ambient_ecs = { path = "../ecs" }

serde = { workspace = true }
toml = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
paste = { workspace = true }
