[package]
edition = "2021"
name = "ambient"
version = { workspace = true }
rust-version = { workspace = true }
repository = "https://github.com/AmbientRun/Ambient"

[dependencies]
ambient_sys = { path = "../crates/sys" }
ambient_animation = { path = "../crates/animation" }
ambient_app = { path = "../crates/app" }
ambient_audio = { path = "../crates/audio" }
ambient_build = { path = "../crates/build" }
ambient_cameras = { path = "../crates/cameras" }
ambient_core = { path = "../crates/core" }
ambient_debugger = { path = "../crates/debugger" }
ambient_decals = { path = "../crates/decals" }
ambient_ecs = { path = "../crates/ecs" }
ambient_editor_derive = { path = "../crates/editor_derive" }
ambient_element = { path = "../crates/element" }
ambient_gizmos = { path = "../crates/gizmos" }
ambient_gpu = { path = "../crates/gpu" }
ambient_input = { path = "../crates/input" }
ambient_meshes = { path = "../crates/meshes" }
ambient_model = { path = "../crates/model" }
ambient_model_import = { path = "../crates/model_import" }
ambient_network = { path = "../crates/network" }
ambient_prefab = { path = "../crates/prefab" }
ambient_physics = { path = "../crates/physics" }
ambient_primitives = { path = "../crates/primitives" }
ambient_project = { path = "../crates/project" }
ambient_renderer = { path = "../crates/renderer" }
ambient_rpc = { path = "../crates/rpc" }
ambient_layout = { path = "../crates/layout" }
ambient_text = { path = "../crates/text" }
ambient_wasm = { path = "../crates/wasm" }
ambient_std = { path = "../crates/std" }
ambient_ui = { path = "../crates/ui" }
ambient_world_audio = { path = "../crates/world_audio" }
ambient_sky = { path = "../crates/sky" }
ambient_water = { path = "../crates/water" }
ambient_window_types = { path = "../crates/window_types" }

tracing-tree = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true }
tracing-log = { workspace = true, optional = true }

anyhow = { workspace = true }
bincode = { workspace = true }
byteorder = { workspace = true }
clap = { workspace = true }
convert_case = { workspace = true }
env_logger = { workspace = true }
futures = { workspace = true }
glam = { workspace = true }
local-ip-address = { workspace = true }
log = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tower-http = { workspace = true }
walkdir = { workspace = true }
image = { workspace = true }
tracing = { workspace = true }

toml_edit = { workspace = true }
paste = { workspace = true }

[dev-dependencies]
glam = { workspace = true }
rusty-hook = "^0.11.2"

[features]
default = ["assimp"]
production = []
profile = ["ambient_app/profile"]
assimp = ["ambient_model_import/russimp"]
tracing = ["tracing-tree", "tracing-subscriber", "tracing-log"]

[target.'cfg(not(target_os = "unknown"))'.dependencies]
axum = { workspace = true }
