[package]
name = "ambient_rect"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_core = { path = "../core" }
ambient_ecs = { path = "../ecs" }
ambient_gpu = { path = "../gpu" }
ambient_meshes = { path = "../meshes" }
ambient_renderer = { path = "../renderer" }
ambient_std = { path = "../std" }
glam = { workspace = true }
wgpu = { workspace = true }
bytemuck = { workspace = true }
