[package]
name = "ambient_ecs_editor"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_ecs = { path = "../ecs" }
ambient_std = { path = "../std" }
ambient_ui = { path = "../ui" }
ambient_core = { path = "../core" }
ambient_element = { path = "../element" }
ambient_renderer = { path = "../renderer" }
env_logger = { workspace = true }
itertools = { workspace = true }
glam = { workspace = true }

[dev-dependencies]
ambient_app = { path = "../app", features = ["profile"] }
ambient_cameras = { path = "../cameras" }
tokio = { workspace = true }
