[package]
name = "ambient_animation"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_sys = { path = "../sys"}
ambient_model = { path = "../model" }
ambient_std = { path = "../std" }
ambient_ecs = { path = "../ecs" }
ambient_element = { path = "../element" }
ambient_editor_derive = { path = "../editor_derive" }
ambient_ui = { path = "../ui" }
ambient_core = { path = "../core" }
glam = { workspace = true }
ordered-float = { workspace = true }
serde = { workspace = true }
async-trait = { workspace = true }
derive_more = { workspace = true }
convert_case = { workspace = true }
itertools = { workspace = true }
anyhow = { workspace = true }
