[package]
edition = "2021"
name = "ambient_api"
description = "The API to the Ambient Runtime"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/ambient_api"
version = { workspace = true }
rust-version = { workspace = true }
readme = "../../../README.md"
repository = "https://github.com/AmbientRun/Ambient"

[dependencies]
ambient_api_macros = { path = "api_macros", version = "0.1.1" }
anyhow = "1.0"
glam = { version = "0.22.0", features = ["rand"] }
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
once_cell = "1.15.0"
paste = "1.0"
rand = "0.8.5"
wasi = "0.11.0"
data-encoding = "2.3.3"
