
[package]
name = "ambient_gpu"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_sys = { path = "../sys" }
ambient_std = { path = "../std" }
bytemuck = { workspace = true }
winit = { workspace = true }
wgpu = { workspace = true }
glam = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
byteorder = { workspace = true }
image = { workspace = true }
itertools = { workspace = true }
ndarray = { workspace = true }
ordered-float = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
parking_lot = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }

[features]
hotload-includes = ['ambient_std/hotload-includes']


[target.'cfg(target_os = "unknown")'.dev-dependencies]
# TODO: use provided webgpu api when released
wgpu = { version = "0.15", features = ["webgl"] }
