[package]
name = "ambient_debugger"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_element = { path = "../element" }
ambient_ui = { path = "../ui" }
ambient_ecs = { path = "../ecs" }
ambient_std = { path = "../std" }
ambient_renderer = { path = "../renderer" }
ambient_gpu = { path = "../gpu" }
ambient_core = { path = "../core" }
ambient_gizmos = { path = "../gizmos" }
ambient_element_component = { path = "../element_component" }
ambient_rpc = { path = "../rpc" }
ambient_network = { path = "../network" }
ambient_ecs_editor = { path = "../ecs_editor" }
ambient_window_types = { path = "../window_types" }
winit = { workspace = true }
glam = { workspace = true }
wgpu = { workspace = true }
log = { workspace = true }
