[package]
name = "raw_text"
edition = "2021"
version = { workspace = true }
publish = false

[dependencies]
ambient_api = { path = "../../../api" }

[lib]
crate-type = ["cdylib"]
required-features = []
