[package]
name = "ambient_water"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_ecs = { path = "../ecs" }
ambient_std = { path = "../std" }
ambient_core = { path = "../core" }
ambient_gpu = { path = "../gpu" }
ambient_gizmos = { path = "../gizmos" }
ambient_meshes = { path = "../meshes" }
ambient_renderer = { path = "../renderer" }
ambient_primitives = { path = "../primitives" }
wgpu = { workspace = true }
glam = { workspace = true }
