
[package]
name = "ambient_editor_derive"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
pretty_assertions = { workspace = true }
itertools = { workspace = true }
syn = { workspace = true }
proc-macro-crate = { workspace = true }
convert_case = { workspace = true }

[dev-dependencies]
ambient_ui = { path = "../ui" }
pretty_assertions = "1.3"
