[package]
name = "tictactoe"
edition = "2021"
version = { workspace = true }
rust-version = { workspace = true }
publish = false

[dependencies]
ambient_api = { path = "../../../api" }
palette = "0.6.1"

[lib]
crate-type = ["cdylib"]
required-features = []
