[package]
name = "ambient_model"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_sys = { path = "../sys" }
ambient_std = { path = "../std" }
ambient_core = { path = "../core" }
ambient_ecs = { path = "../ecs" }
ambient_renderer = { path = "../renderer" }
ambient_meshes = { path = "../meshes" }
ambient_gpu = { path = "../gpu" }
ambient_editor_derive = { path = "../editor_derive" }
ambient_ui = { path = "../ui" }
futures = { workspace = true }
glam = { workspace = true }
itertools = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
wgpu = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
bytemuck = { workspace = true }
async-trait = { workspace = true }
url = { workspace = true }

[features]
hotload-includes = ['ambient_std/hotload-includes']
