[package]
name = "ambient_layout"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_ecs = { path = "../ecs" }
ambient_core = { path = "../core" }
ambient_input = { path = "../input" }
glam = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
