[package]
name = "ambient_wasm"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_sys = { path = "../sys" }
ambient_animation = { path = "../animation" }
ambient_app = { path = "../app" }
ambient_core = { path = "../core" }
ambient_ecs = { path = "../ecs" }
ambient_input = { path = "../input" }
ambient_network = { path = "../network" }
ambient_prefab = { path = "../prefab" }
ambient_physics = { path = "../physics" }
ambient_project = { path = "../project" }
ambient_std = { path = "../std" }
physxx = { path = "../../libs/physxx" }

anyhow = { workspace = true }
async-trait = { workspace = true }
data-encoding = { workspace = true }
chrono = { workspace = true }
flume = { workspace = true }
fs_extra = { workspace = true }
glam = { workspace = true }
indexmap = { workspace = true }
indoc = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
parking_lot = { workspace = true }
profiling = { workspace = true }
reqwest = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
slotmap = { workspace = true }

wasi-common = { workspace = true }
wasmtime-wasi = { workspace = true }
wasmtime = { workspace = true }
wit-bindgen-host-wasmtime-rust = { git = "https://github.com/bytecodealliance/wit-bindgen.git", rev = "181093b58f49b194ee34be2d986d737f4f553d3d" }

[target.'cfg(windows)'.build-dependencies]
dunce = "1.0"

[build-dependencies]
ambient_std = { path = "../std", default-features = false }
# make sure this is synchronised with the version used for the host
wit-bindgen-core = { git = "https://github.com/bytecodealliance/wit-bindgen.git", rev = "181093b58f49b194ee34be2d986d737f4f553d3d" }
wit-bindgen-gen-guest-rust = { git = "https://github.com/bytecodealliance/wit-bindgen.git", rev = "181093b58f49b194ee34be2d986d737f4f553d3d" }
