[package]
name = "ambient_cameras"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_std = { path = "../std" }
ambient_ecs = { path = "../ecs" }
ambient_core = { path = "../core" }
ambient_element = { path = "../element" }
winit = { workspace = true }
derive_more = { workspace = true }
glam = { workspace = true }
