[package]
name = "ambient_sky"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_ecs = { path = "../ecs" }
ambient_std = { path = "../std" }
ambient_core = { path = "../core" }
ambient_gpu = { path = "../gpu" }
ambient_gizmos = { path = "../gizmos" }
ambient_meshes = { path = "../meshes" }
ambient_renderer = { path = "../renderer" }
wgpu = { workspace = true }
noise = { workspace = true }
glam = { workspace = true }
bytemuck = { workspace = true }
derive_more = { workspace = true }
ordered-float = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
ambient_cameras = { path = "../cameras" }
tokio = { workspace = true }

[features]
hotload-includes = ['ambient_std/hotload-includes']
