[package]
name = "rect"
edition = "2021"
version = { workspace = true }
rust-version = { workspace = true }
publish = false

[dependencies]
ambient_api = { path = "../../../api" }
ambient_element = { path = "../../../../../crates/element", default-features = false, features = [
    "guest",
] }
ambient_ui_components = { path = "../../../../../crates/ui_components" }
ambient_guest_bridge = { path = "../../../../../crates/guest_bridge", default-features = false, features = [
    "guest",
] }

[lib]
crate-type = ["cdylib"]
required-features = []
