[package]
name = "ambient_editor"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_sys = { path = "../sys" }
ambient_app = { path = "../app" }
ambient_meshes = { path = "../meshes" }
ambient_core = { path = "../core" }
ambient_element = { path = "../element" }
ambient_ui = { path = "../ui" }
ambient_ecs = { path = "../ecs" }
ambient_network = { path = "../network" }
ambient_std = { path = "../std" }
ambient_gpu = { path = "../gpu" }
ambient_renderer = { path = "../renderer" }
ambient_input = { path = "../input" }
ambient_rpc = { path = "../rpc" }
ambient_intent = { path = "../intent" }
ambient_ecs_editor = { path = "../ecs_editor" }
ambient_physics = { path = "../physics" }
ambient_primitives = { path = "../primitives" }
ambient_model = { path = "../model" }
ambient_animation = { path = "../animation" }
ambient_cameras = { path = "../cameras" }
ambient_prefab = { path = "../prefab" }
ambient_decals = { path = "../decals" }
ambient_world_audio = { path = "../world_audio" }
ambient_terrain = { path = "../terrain" }
ambient_naturals = { path = "../naturals" }
ambient_window_types = { path = "../window_types" }
physxx = { path = "../../libs/physxx" }
glam = { workspace = true }
itertools = { workspace = true }
ordered-float = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
profiling = { workspace = true }
closure = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }
bytemuck = { workspace = true }
image = { workspace = true }
bitflags = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }
open = { workspace = true }
arboard = { workspace = true }
which = { workspace = true }
parking_lot = { workspace = true }
chrono = { workspace = true }
env_logger = { workspace = true }
indexmap = { workspace = true }
futures-signals = { workspace = true }
derive_more = { workspace = true }

[features]
hotload-includes = [
    'ambient_std/hotload-includes',
    'ambient_decals/hotload-includes',
]

[target.'cfg(not(target_os = "unknown"))'.dependencies]
tokio = { workspace = true }
quinn = { workspace = true }
