
[package]
name = "ambient_element_component"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
itertools = { workspace = true }
syn = { workspace = true }
proc-macro-crate = { workspace = true }
