[package]
name = "ambient_network"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_ecs = { path = "../ecs" }
ambient_sys = { path = "../sys" }
ambient_rpc = { path = "../rpc" }
ambient_std = { path = "../std" }
ambient_core = { path = "../core" }
ambient_gizmos = { path = "../gizmos" }
ambient_gpu = { path = "../gpu" }
ambient_ui = { path = "../ui" }
ambient_renderer = { path = "../renderer" }
ambient_element = { path = "../element" }
ambient_app = { path = "../app" }
itertools = { workspace = true }
dashmap = { workspace = true }
serde = { workspace = true }
futures = { workspace = true }
rand = { workspace = true }
thiserror = { workspace = true }
# Note: can't be in workspace as it stops wasm from compiling
bincode = { workspace = true }
glam = { workspace = true }
winit = { workspace = true }
profiling = { workspace = true }
log = { workspace = true }
bytes = { workspace = true }
parking_lot = { workspace = true }
wgpu = { workspace = true }
flume = { workspace = true }
anyhow = { workspace = true }
manual_future = { workspace = true }
tracing = { workspace = true }
once_cell = { workspace = true }

[target.'cfg(not(target_os = "unknown"))'.dependencies]
quinn = { workspace = true }
rustls = { workspace = true }
tokio-util = "0.7"
tokio = { workspace = true }
