
[package]
name = "ambient_element"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_guest_bridge = { path = "../guest_bridge" }
ambient_element_component = { path = "../element_component" }
cb = { path = "../../libs/cb" }
friendly_id = { path = "../../libs/friendly_id" }

ambient_sys = { path = "../sys", optional = true }
ambient_core = { path = "../core", optional = true }
tokio = { workspace = true, optional = true }

parking_lot = { workspace = true }
itertools = { workspace = true }
as-any = { workspace = true }
dyn-clonable = { workspace = true }
derivative = { workspace = true }
tracing = { workspace = true }
profiling = { workspace = true }
atomic_refcell = { workspace = true }
futures = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }

[features]
default = ["native"]
native = ["ambient_sys", "ambient_core",  "ambient_guest_bridge/native",  "tokio"]
guest = ["ambient_guest_bridge/guest"]
