[package]
name = "ambient_web"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Web client for ambient"
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_sys = { path = "../crates/sys", features = [
    "console_error_panic_hook",
] }
ambient_core = { path = "../crates/core" }
ambient_ecs = { path = "../crates/ecs" }
ambient_app = { path = "../crates/app" }

anyhow = { workspace = true }

wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
tracing-subscriber = { version = "0.3", features = ["time"] }
tracing-web = "0.1"
time = { version = "0.3", features = ["wasm-bindgen"] }
chrono = { workspace = true, features = ["wasmbind"] }

getrandom = { version = "0.2.8", features = ["js"] }
web-sys = { version = "0.3.61", features = [
    "CanvasRenderingContext2d",
    "Document",
    "Element",
    "HtmlCanvasElement",
    "HtmlDocument",
    "Performance",
    "Window",
] }

futures = { workspace = true }
tracing = { workspace = true }
